# Generated by Django 3.2.6 on 2021-09-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210820_1742'),
        ('boards', '0002_auto_20210823_1509'),
    ]

    operations = [
    ]
