# Generated by Django 3.2.6 on 2021-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_merge_0002_auto_20210820_1742_0002_auto_20210823_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
